### ISSUE TITLE
mt成人区

### ISSUE THREAD

**Issue by Tony-Yes** [KesaubeEire/PT_TorrentList_Masonry#1]
成人区能加个屏蔽gv的开关吗 有点辣眼啊

**Comment by KesaubeEire** [comment]
可以的, 我正在重构, 这个需求我记下了

**Comment by KesaubeEire** [comment]
> 成人区能加个屏蔽gv的开关吗 有点辣眼啊

我已经重构了一版新的脚本, 为 MT 特意加了过滤 gv 的功能, 默认是开启的.
[github](https://github.com/KesaubeEire/PT_Masonry_View_Svelte)
[油猴](https://greasyfork.org/zh-CN/scripts/470821)

**Comment by Tony-Yes** [comment]
新版本 返回上一页是直接返回首页 这个是bug吗

**Comment by KesaubeEire** [comment]
> 新版本 返回上一页是直接返回首页 这个是bug吗

方便给个截图或者啥的么, 我不知道怎么复现

**Comment by Tony-Yes** [comment]
就是点进种子界面之后 鼠标或者点击返回上一页的时候会直接跳转到首页。我发现点最左侧边上就能正常返回上一页了

**Comment by Tony-Yes** [comment]
鼠标点击我标记红色部分里面那部分就能正常返回上一页。直接返回上一页是跳转首页的
![](https://tu.kp.al/2023/07/24/%25pn_2023-07-24_19-34-42.png)
